language: python
python:
  - '3.8'
before_script:
  - pip install -r requirements.txt
  - psql -c 'create database nutella;' -U postgres
  - cd search/tests
branches:
    only:
        - test
            
env: DJANGO_SETTINGS_MODULE="nutella_project.settings.travis"

services:
  - postgresql

script:
  - pytest

